name-template: 'v$NEXT_PATCH_VERSION'
tag-template: 'v$NEXT_PATCH_VERSION'

# Draft notes; Commitizen still controls actual version bump & CHANGELOG.
change-template: '- $TITLE (#$NUMBER)'

categories:
  - title: '✨ Features'
    labels:
      - feat
      - feature
      - enhancement
  - title: '🐞 Fixes'
    labels:
      - fix
      - bug
      - bugfix
  - title: '⚙️ Performance'
    labels:
      - perf
      - performance
  - title: '🧹 Refactoring'
    labels:
      - refactor
  - title: '🧪 Tests'
    labels:
      - test
      - tests
  - title: '📝 Documentation'
    labels:
      - docs
  - title: '🔐 Security'
    labels:
      - security
      - 'type: security'
  - title: '🧰 Tooling / Chore'
    labels:
      - chore
      - infra
      - build
      - ci

exclude-labels:
  - skip-changelog

replacers:
  - search: '^(feat|fix|perf|refactor|docs|test|chore)(\(.+?\))?:\s*'
    replace: ''

template: |
  ## Release Notes

  $CHANGES

  ## Installation
  ```bash
  pip install tenets==$VERSION
  ```

  ## Links
  - Docs: https://docs.tenets.dev
  - Repo: https://github.com/jddunn/tenets
  - Security: SECURITY.md

  _Generated by Release Drafter._
